[package]
name = "price_tracker"
version = "0.1.0"
authors = ["Jurij Robba <jurij.robba@vernocte.org>"]
edition = "2018"

[dependencies]

tokio-tungstenite = "0.10.1"
tokio = { version = "0.2", features = ["full"] }
tungstenite = "0.11"
futures = "0.3"
url = "2.1"
json = "0.12.4"
